// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQcWgHlKBPY62n3NThFkp9QOd3833W6uA',
    appId: '1:432974365154:web:706ed4ef46af2d3c3b79bb',
    messagingSenderId: '432974365154',
    projectId: 'proyecto-e15e4',
    authDomain: 'proyecto-e15e4.firebaseapp.com',
    storageBucket: 'proyecto-e15e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7Wh_v-QmwGkAYHj5gU9OinbQniwDQsU',
    appId: '1:432974365154:android:664ec25f0a54c04f3b79bb',
    messagingSenderId: '432974365154',
    projectId: 'proyecto-e15e4',
    storageBucket: 'proyecto-e15e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRFAyiaNt8A1AolLZIoZhyBEu6u4fjYc',
    appId: '1:432974365154:ios:340cd1b2cbab230d3b79bb',
    messagingSenderId: '432974365154',
    projectId: 'proyecto-e15e4',
    storageBucket: 'proyecto-e15e4.appspot.com',
    iosBundleId: 'com.example.todolistFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRFAyiaNt8A1AolLZIoZhyBEu6u4fjYc',
    appId: '1:432974365154:ios:340cd1b2cbab230d3b79bb',
    messagingSenderId: '432974365154',
    projectId: 'proyecto-e15e4',
    storageBucket: 'proyecto-e15e4.appspot.com',
    iosBundleId: 'com.example.todolistFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQcWgHlKBPY62n3NThFkp9QOd3833W6uA',
    appId: '1:432974365154:web:b3964a36142859d13b79bb',
    messagingSenderId: '432974365154',
    projectId: 'proyecto-e15e4',
    authDomain: 'proyecto-e15e4.firebaseapp.com',
    storageBucket: 'proyecto-e15e4.appspot.com',
  );

}